### ISSUE TITLE
drawer on top "Without scroll view adjustment"

### ISSUE THREAD

**Issue by coanag** [DrummerB/BFNavigationBarDrawer#4]
Hello,
thank you for this solution.
Can you provide a the configuration, so when the drawer is scrolling down not to push the tableview scroller(like the "Without scroll view adjustment" in your image)?

Thanks in advance

**Comment by DrummerB** [comment]
Just don't set the scrollView property of the drawer. 
In the demo app, comment out this line:

```
drawer.scrollView = self.tableView;
```

Does this help?

**Comment by coanag** [comment]
This is what I'm looking for.Thank you.
(By the way I'm testing it, so when you finish scrolling down the tableview , to trigger the "showFromNavigationBar" method and it works great.(like the Facebook app)

Thanks again for the immediate response.
