### ISSUE TITLE
Does not animate / work properly on device rotations

### ISSUE THREAD

**Issue by hokster7** [DrummerB/BFNavigationBarDrawer#5]
Thanks for `BFNavigationBarDrawer` — it's probably saved me hours of trying to get a toolbar attached to the navigation bar.

When the toolbar is shown in either landscape or portrait orientations, it's fine.
However, when you rotate the device 90 degrees, it's obvious that the toolbar remains oblivious.

In particular, I have a segmented control placed bang in the middle of the toolbar so it's very obvious that the toolbar has not reacted to the new orientation.

My workaround for this is something like the following:

```
- (void)didRotateFromInterfaceOrientation:(UIInterfaceOrientation)fromInterfaceOrientation {
    [super didRotateFromInterfaceOrientation:fromInterfaceOrientation];
    // 
    [self.toolbar hideAnimated:NO];
    [self.toolbar showFromNavigationBar:self.navigationController.navigationBar animated:NO];
}
```

It's not perfect: you see the segmented control 'jumping' into its correct position this way.

I expect the toolbar to react naturally to bounds changes like the one caused by a device  rotation.

**Comment by DrummerB** [comment]
Hi, thanks again, for reporting. This should be fixed now. I changed the layout from manual to Auto Layout, so it behaves correctly during rotations.

**Comment by hokster7** [comment]
Excellent — I'll give it a shot.
