### ISSUE TITLE
showFromNavigationBar:animated: is not idempotent

### ISSUE THREAD

**Issue by hokster7** [DrummerB/BFNavigationBarDrawer#6]
If you call this method twice after having set a `scrollView`:

``` objc
    self.toolbar.scrollView = self.collectionView;
    ...
    [self.toolbar showFromNavigationBar:self.navigationController.navigationBar animated:NO];
[self.toolbar showFromNavigationBar:self.navigationController.navigationBar animated:NO];
```

The `contentInset` continues to be padded from the top multiple times.

I expect the toolbar to remember its showing state for the nominated navigationBar. (Or, indeed, know what bar it was previously shown from as well) It should not augment the `contentInset` multiple times.

**Comment by DrummerB** [comment]
Thanks for reporting this. I fixed this now. If you show the drawer from the same navigation bar, nothing happens and the content offset stays the same.

**Comment by hokster7** [comment]
Thanks for fixing it.

The same thing with `hideAnimated:`. I've found a strange effect in my program where my content just keeps shifting higher and higher up. This is because I had stuck the call into `viewWillDisappear:` which, under my circumstances, gets called twice. :/

Understandably I should make sure that it only gets called once, but it's tricky.

**Comment by DrummerB** [comment]
Alright, should be fixed now too. Thanks.

**Comment by hokster7** [comment]
Awesome cheers!
